language: scala
jdk: oraclejdk8
scala:
   - 2.11.4
   - 2.11.12

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"

branches:
  only:
    - master
    - /^v[0-9]/

script:
   - sbt clean test

before_cache:
   - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
   - find $HOME/.sbt -name "*.lock" -delete

notifications:
  email:
    on_success: never
